In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4])
b = np.array([10,20,30,40])

print(a,b)

[1 2 3 4] [10 20 30 40]


In [7]:
#mathematical operations

# addition
print('add arrays', a + b)
# subtraction
print('subtract arrays', a - b)
# multiplication
print('multiply arrays', a * b)

# universal funcs

print('square root', np.sqrt(a))

# exponential

print('exponential', np.exp(b))

add arrays [11 22 33 44]
subtract arrays [ -9 -18 -27 -36]
multiply arrays [ 10  40  90 160]
square root [1.         1.41421356 1.73205081 2.        ]
exponential [2.20264658e+04 4.85165195e+08 1.06864746e+13 2.35385267e+17]


In [14]:
arr1 = np.array([5,10,15])
arr2 = np.array([2,4,6])

print('add', arr1 + arr2)

print('subtract', arr1 - arr2)

print('multiply', arr1 * arr2)

print('divide', arr1 / arr2)

print('arr1 cubed', arr1 ** 3)



add [ 7 14 21]
subtract [3 6 9]
multiply [10 40 90]
divide [2.5 2.5 2.5]
arr1 cubed [ 125 1000 3375]


In [16]:
# broadcasting

arraybc = np.array([1,2,3,4,5])

print('arr + 10', arraybc + 10)
#broadcasting adds the number to each element in the array.

arr + 10 [11 12 13 14 15]


In [19]:
matrix = np.array([[1,2,3],[4,5,6]])
print(matrix)

[[1 2 3]
 [4 5 6]]


In [22]:
# add new array 10,20,30 to the mat

# adds 10 to 1, 20 to 2, 30 to 3.
# then adds 10 to 4, 20 to 5, and 30 to 6.
print(matrix + np.array([10,20,30]))

[[11 22 33]
 [14 25 36]]


In [30]:
arrtomul = np.array([2,4,6,8])

print(arrtomul * 0.5)



[1. 2. 3. 4.]


In [25]:
threebythree = np.zeros((3,3))
print(threebythree)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [27]:
addnums = threebythree + np.array([1,2,3])
print(addnums)

[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]


In [32]:
addnums2 = np.ones((2,3))

print(addnums2 + 10)



[[11. 11. 11.]
 [11. 11. 11.]]


In [33]:
# create random ints

dice = np.random.randint(1,7, size=10)
print(dice)


[1 5 2 1 3 2 6 5 5 3]


In [36]:
dicerolls = np.random.randint(1,7, size=20)

print(dicerolls)
print(np.min(dicerolls))
print(np.max(dicerolls))

[3 4 4 3 5 4 4 2 5 5 4 2 5 6 6 4 1 4 3 3]
1
6


In [42]:
ranfloats = np.random.uniform(low=0, high=10, size=10)
print(ranfloats)

[5.21543767 2.703864   5.18451308 2.43469669 8.1284405  7.71616569
 4.15871238 6.42316564 9.0017796  0.1618855 ]


In [49]:
moreranfloats = np.random.rand(1000)
print(moreranfloats[0:10])

[0.17944619 0.31723939 0.36182353 0.92563429 0.33985836 0.80551159
 0.8224778  0.64162064 0.00794132 0.17123699]


In [50]:
dice = np.random.randint(1, 7, size=50)
print(dice)

[1 5 4 2 3 5 2 6 3 4 4 1 1 1 1 1 2 5 5 6 5 1 5 3 2 5 3 1 6 2 2 6 3 5 3 1 5
 4 5 1 3 5 6 5 3 3 3 5 1 3]


In [51]:
print('sum: ', np.sum(dice))

sum:  167


In [52]:
print('mean: ', np.mean(dice))

mean:  3.34


In [53]:
print('median: ', np.median(dice))

median:  3.0


In [54]:
print('standard deviation: ', np.std(dice))

standard deviation:  1.7042300314218148


In [55]:
print('min: ', np.min(dice))
print('max: ', np.max(dice))

min:  1
max:  6
