In [3]:
import numpy as np

numbers = [1, 2, 3, 4]
array = np.array(numbers)

print(array)

[1 2 3 4]


In [4]:
doubled = array * 2
print(doubled)

[2 4 6 8]


In [5]:
#zeros
zeros = np.zeros((2,3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]]


In [6]:
#ones
ones = np.ones((3,))
print(ones)

[1. 1. 1.]


In [7]:
#range
range_array = np.arange(0,10,2)
print(range_array)

[0 2 4 6 8]


In [8]:
#array 1-9
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(a)

[1 2 3 4 5 6 7 8 9]


In [10]:
fourones = np.ones((4,4))
print(fourones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [12]:
betweenzeroandone = np.linspace(0,1)
print(betweenzeroandone)

[0.         0.02040816 0.04081633 0.06122449 0.08163265 0.10204082
 0.12244898 0.14285714 0.16326531 0.18367347 0.20408163 0.2244898
 0.24489796 0.26530612 0.28571429 0.30612245 0.32653061 0.34693878
 0.36734694 0.3877551  0.40816327 0.42857143 0.44897959 0.46938776
 0.48979592 0.51020408 0.53061224 0.55102041 0.57142857 0.59183673
 0.6122449  0.63265306 0.65306122 0.67346939 0.69387755 0.71428571
 0.73469388 0.75510204 0.7755102  0.79591837 0.81632653 0.83673469
 0.85714286 0.87755102 0.89795918 0.91836735 0.93877551 0.95918367
 0.97959184 1.        ]


In [17]:
array5 = np.array([10,20,30,40,50])


#indexing

#get first element
print(array5[0])

#get last element
print(array5[-1])

#slicing

#first 3
print(array5[0:3])

#every other element
print(array5[::2])

10
50
[10 20 30]
[10 30 50]


In [19]:
#2d arrays 

# indexing/slicing 

matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [20]:
# print element at row 1 col 2

print(matrix[0,1])

2


In [22]:
#print every second number from every row


print(matrix[:,1])
# the first position accesses the rows, and it's all of them because ':' gets everything. we want the second element in each row,
# which in columns is index 1.

[2 5 8]


In [23]:
# every row, 3rd number

print(matrix[:,2])

[3 6 9]


In [29]:
slicingarray = np.arange(1,11)
print(slicingarray)

[ 1  2  3  4  5  6  7  8  9 10]


In [31]:
print(slicingarray)

slicedarray = slicingarray[-5:]
print(slicedarray)

[ 1  2  3  4  5  6  7  8  9 10]
[ 6  7  8  9 10]


In [36]:
print(matrix[:2])
#first 2 rows

[[1 2 3]
 [4 5 6]]


In [37]:
print(matrix[-2:,-2:])
#2x2 sub-matrix

[[5 6]
 [8 9]]


In [40]:
#reshaping

reshapearray = np.arange(1,13)
print(reshapearray)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [41]:
reshaped = reshapearray.reshape(3,4)
print(reshaped)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [42]:
#extract submatrix top left 2x2

print(reshaped[:2, :2])

[[1 2]
 [5 6]]


In [43]:
flat = reshaped.flatten()
print(flat)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [46]:
matrixagain = flat.reshape(3,4)
print(matrixagain)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [58]:
#middle cols
print(matrixagain[:, 1:3])

[[ 2  3]
 [ 6  7]
 [10 11]]


In [49]:
flatagain = matrixagain.flatten()
print(flatagain)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [53]:
anotherarray = np.arange(1,65)
anothermatrix = anotherarray.reshape(8,8)
print(anothermatrix)

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]
 [25 26 27 28 29 30 31 32]
 [33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48]
 [49 50 51 52 53 54 55 56]
 [57 58 59 60 61 62 63 64]]


In [56]:
print(anothermatrix[2:, 2:6])

[[19 20 21 22]
 [27 28 29 30]
 [35 36 37 38]
 [43 44 45 46]
 [51 52 53 54]
 [59 60 61 62]]


In [57]:
anotherflatarray = anothermatrix.flatten()
print(anotherflatarray)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64]
